### ISSUE TITLE
Configuration bug

### ISSUE THREAD

**Issue by TorgeirUstad** [EMMC-ASBL/oteapi-core#34]
After commit dc1ec0d, creating an ImageDataParseStrategy fails with message

`TypeError: 'DataCacheConfig' object is not subscriptable`

on line 45 in "image_jpeg.py".

**Comment by CasperWA** [comment]
The issue is the mixed type for `configuration` - specifically for the `ResourceConfig` model: `Union[DataCacheConfig, Dict[str, Any]`.

There are two solutions in my opinion:
1. Create a utility function to "get" attributes from an object that may be either a pydantic model or a dictionary.
2. Use one or the other throughout for the repeating `configuration` attribute in the configs. Preferrably use pydantic models - one can simulate the flexibility of a dictionary by allowing the addition of extra attributes.

I personally prefer the latter solution.
