### ISSUE TITLE
Consider removing the `create_*_strategy()` functions

### ISSUE THREAD

**Issue by CasperWA** [EMMC-ASBL/oteapi-core#57]
We can use the `create_strategy()` function instead.

**Comment by jesper-friis** [comment]
Good idea. That is more flexible and avoids bloating the API

**Comment by TorgeirUstad** [comment]
I have just spent some time on trying to make a unit test for factories.py, and it was a nightmare. There are so many issues:

* In `create_resource_strategy`, the call to `make_strategy` demands that the *optional* field `accessService` has been set, or line 132 raises a `KeyError`.
* On line 188 the call `strategy_kwargs = strategy_type.get_make_strategy_kwargs()` needs to include `config` as an argument...
* ...But even then, if one tries to call `create_strategy()`, line 188 still causes problems, because `get_make_strategy_kwargs()` is decorated with `@lru_cache`, which demands that the `config` object is hashable, which the configuration models aren't.

So, by all means, **please rewrite this module.**

**Comment by jesper-friis** [comment]
factories.py has been completely refactored in PR #47. I see that Casper has written tests for factories.py and entry_points.py with 100% coverage.
